### ISSUE TITLE
Change the printed text to "Goodbye World!"

### ISSUE THREAD

**Issue by ohtohalla** [KSundstrom/team-1-nlp-app#1]
Please modify the code to print "Goodbye World!" instead of "Hello World!".

**Comment by KSundstrom** [comment]
Okay, good idea, done.

**Comment by KSundstrom** [comment]
Redid it with the correct commit message.

**Comment by KSundstrom** [comment]
@ohtohalla : Please review my code

**Comment by ohtohalla** [comment]
Is there some way you could make it pop more @KSundstrom?

**Comment by KSundstrom** [comment]
No.

**Comment by ohtohalla** [comment]
Dammit ok.
