### ISSUE TITLE
See if the program works on some other languages as well

### ISSUE THREAD

**Issue by ohtohalla** [KSundstrom/team-1-nlp-app#10]
If you like, you can use some other data, for instance a Wikipedia dump for some other language, such as Finnish: https://linguatools.org/tools/corpora/wikipedia-monolingual-corpora/. First you need to download a Wikipedia XML file. Then you need to uncompress it with bunzip2. Then you need to convert the XML format to plain text using the Perl script xml2txt.pl, which is available for download on the web page. You need to use the option -articles in order to preserve the article tags: perl xml2txt.pl -articles INPUT_FILE.xml OUTPUT_FILE.txt.

**Comment by KSundstrom** [comment]
I've downloaded the Finnish Wikipedia corpus and unzipped it. I'm now trying to convert the XML with the Perl script.

**Comment by KSundstrom** [comment]
Created a truncated Finnish Wikipedia corpus, added it, and switched the search engine to use it as article source. Everything seems to work exactly like with the English corpora. Please review, @ohtohalla
