### ISSUE TITLE
Use relevance ranking based on tf-idf instead of boolean search

### ISSUE THREAD

**Issue by ohtohalla** [KSundstrom/team-1-nlp-app#11]
Create a copy of your source code for the Boolean search engine and modify the code to use relevance ranking based on tf-idf and cosine similarity instead.

**Comment by KSundstrom** [comment]
This is now working. @ohtohalla please review.

**Comment by ohtohalla** [comment]
Seems to be working for me, too! Thank you for your work! Closing this now
