### ISSUE TITLE
Make an it an option to select either boolean or ranked search

### ISSUE THREAD

**Issue by ohtohalla** [KSundstrom/team-1-nlp-app#12]
Do not throw away your Boolean search engine. Just create another alternative. You can also have both search engines in the same program and ask the user which one to use. Or you can have your program automatically check whether there are any Boolean operators in the query, and in that case run Boolean search, otherwise tf-idf based search.

**Comment by KSundstrom** [comment]
Created combined search engine, asking the user which engine to use. @ohtohalla please review. It would probably still be an enhancement to automatically use the Boolean engine if there are Boolean operators in the query.

**Comment by ohtohalla** [comment]
This also seems to be working now! Closing this

**Comment by ohtohalla** [comment]
Created a new issue for the added functionality #19
