### ISSUE TITLE
Implement the user input loop

### ISSUE THREAD

**Issue by ohtohalla** [KSundstrom/team-1-nlp-app#5]
The queries should not be hard-coded. Instead your program should ask the user to type the query. Make this run in a loop, so that the user can run as many queries they like. Also come up with some user input that tells the program to quit, such as an empty string or a specific keyword.

**Comment by KSundstrom** [comment]
Implemented, with an empty string exitting the loop.

**Comment by KSundstrom** [comment]
Do you think the current implementation is sufficient @ohtohalla ?

**Comment by ohtohalla** [comment]
This works as intended in my opinion. I'll mark this as closed.
