### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by ohtohalla** [KSundstrom/team-1-nlp-app#7]
If you just copy the code from the tutorial, your program will crash if you enter a word (term) that does not occur in any document in the collection. Modify your program to work correctly also in the case that a term is unknown. For instance, what documents should be retrieved for a search such as: (1) "unknownweirdword", (2) "NOT unknownweirdword", or (3) "unknownweirdword OR this"?  (If this is too difficult, don't get stuck here, but come back to it later.)

**Comment by ohtohalla** [comment]
@KSundstrom @lidafr Please review my code. I implemented simple error handling to the search script. Do you think it is sufficient as such?

**Comment by KSundstrom** [comment]
Thank you! It seems to be sufficient for the assignment.

**Comment by KSundstrom** [comment]
We still need to modify the code to correctly handle "NOT unknownweirdword" and "unknownweirdword OR this"; the current error handling returns "Your search provided no results, please try another query" for _all_ queries containing an word that is not extant in the documents.
