### ISSUE TITLE
Make sure that all alpha-numerical words are indexed

### ISSUE THREAD

**Issue by ohtohalla** [KSundstrom/team-1-nlp-app#8]
Have you noticed that not all words in the toy data were actually indexed by the code in the tutorial? Which ones? Would you like to index all words containing alpha-numerical characters? Can you solve that? The answer can be found here: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html  (Again, don't waste time on this one if it is too difficult, but return to it later.)

**Comment by ohtohalla** [comment]
The script should now also index tokens of length 1. The notion about "not" not working was a user error and was due to me writing nonstandard booleans in the query. 

We should still implement a feature so that "not" in between words mean "and not".

@KSundstrom @lidafr Please review my code

**Comment by KSundstrom** [comment]
This issue seems to be correctly and fully solved, thanks! Closing. (The not-for-and-not shorthand we can probably return to later if we feel like it.)
