### ISSUE TITLE
Make sure that the program works on "real world data"™

### ISSUE THREAD

**Issue by ohtohalla** [KSundstrom/team-1-nlp-app#9]
This task is important. You need to index some "real" documents from a text file. When you run your program, it should start by reading document contents from a file and index these documents. After this, the user should be able to type queries and retrieve matching documents. Initially, you can use our example data sets: One contains 100 articles extracted from English Wikipedia and the other contains 1000 articles extracted from English Wikipedia (with topics mostly starting with the letter A). When you read these files, you need to produce a list of strings, such that an entire article (document) is in one string. You can locate the boundaries between two articles from the </article> tag, which always occurs on a line of its own in the file. The text is UTF-8 encoded.

**Comment by KSundstrom** [comment]
This is now implemented in two different ways; the user starts by choosing the data source. Please review my latest changes, @ohtohalla
